plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = mod_version
group = mod_group_id

base {
    archivesName = 'PixelmonEffectiveness-1.21.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    version = neo_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "Pixelmon Maven"
        url = "https://maven.reforged.gg/releases"
    }
}

dependencies {
    // Pixelmon Reforged for 1.21.1
    compileOnly "com.pixelmonmod.pixelmon:Pixelmon-1.21.1:${pixelmon_version}-universal"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
